import "server-only";
import { randomUUID } from "node:crypto";
import { database } from "./database";
import type { z } from "zod";
import { checkoutSchema, canTransitionOrder, type OrderStatus } from "@/domain/order";
import { enqueueNotification } from "./notifications";
type CheckoutInput = z.infer<typeof checkoutSchema>;
export type CreatedOrder={orderId:string;totalCents:number;deliveryFeeCents:number;providerReference:string|null;currency:"SGD";items:Array<{name:string;quantity:number;unitPriceCents:number}>};
export type ManagedOrder={orderId:string;customerName:string;customerEmail:string;customerPhone:string;deliveryAddress:string;status:OrderStatus;paymentMethod:string;totalCents:number;currency:string;fulfilmentMethod:string|null;requestedForDate:string|null;orderNotes:string|null;createdAtUtc:string;version:number;items:Array<{orderId:string;name:string;quantity:number;unitPriceCents:number}>;events:Array<{orderId:string;fromStatus:string|null;toStatus:string;occurredAtUtc:string}>};
export async function createOrder(input: CheckoutInput): Promise<CreatedOrder> {
  const sql=database();
  return sql.begin(async tx=>{
    const existing=await tx`select customer_order_id as "orderId",total_amount_cents as "totalCents",delivery_fee_cents as "deliveryFeeCents",payment_provider_reference as "providerReference" from customer_order where checkout_request_key=${input.checkoutRequestKey}`;
    if(existing[0]){const items=await tx`select product_name_snapshot as name,quantity,unit_price_cents as "unitPriceCents" from customer_order_item where customer_order_id=${existing[0].orderId}`;return{orderId:String(existing[0].orderId),totalCents:Number(existing[0].totalCents),deliveryFeeCents:Number(existing[0].deliveryFeeCents),providerReference:existing[0].providerReference?String(existing[0].providerReference):null,currency:"SGD" as const,items:items.map(item=>({name:String(item.name),quantity:Number(item.quantity),unitPriceCents:Number(item.unitPriceCents)}))}}
    const rules=await tx`select collection_enabled,delivery_enabled,delivery_fee_cents,minimum_order_cents,lead_time_days,maximum_advance_days,blackout_dates::text[] from ordering_rule where rule_key='storefront' for share`;
    const rule=rules[0];if(!rule)throw new Error("ORDERING_UNAVAILABLE");
    if(input.fulfilmentMethod==="collection"&&!rule.collection_enabled)throw new Error("FULFILMENT_UNAVAILABLE");if(input.fulfilmentMethod==="delivery"&&!rule.delivery_enabled)throw new Error("FULFILMENT_UNAVAILABLE");
    const requested=new Date(input.requestedForDate+"T00:00:00Z"),today=new Date();today.setUTCHours(0,0,0,0);const days=Math.round((requested.getTime()-today.getTime())/86400000);if(days<rule.lead_time_days||days>rule.maximum_advance_days||rule.blackout_dates.includes(input.requestedForDate))throw new Error("DATE_UNAVAILABLE");
    const products=await tx`select product_id as id,name,price_cents as "priceCents" from product where product_id in ${tx(input.items.map(i=>i.productId))} and status='published'`;
    const pricedItems=input.items.map(item=>{const product=products.find(row=>row.id===item.productId);if(!product)throw new Error("PRODUCT_NOT_FOUND");return{...item,name:product.name as string,unitPriceCents:product.priceCents as number,lineTotalCents:(product.priceCents as number)*item.quantity}});
    const subtotal=pricedItems.reduce((sum,item)=>sum+item.lineTotalCents,0);if(subtotal<rule.minimum_order_cents)throw new Error("MINIMUM_ORDER");const deliveryFeeCents=input.fulfilmentMethod==="delivery"?rule.delivery_fee_cents:0,totalCents=subtotal+deliveryFeeCents,orderId=randomUUID();
    await tx`insert into customer_order (customer_order_id,customer_name,customer_email,customer_phone,delivery_address,status,payment_method,total_amount_cents,currency_code,fulfilment_method,requested_for_date,order_notes,delivery_fee_cents,checkout_request_key) values (${orderId},${input.customerName},${input.customerEmail},${input.customerPhone},${input.deliveryAddress},'pending_payment','visa',${totalCents},'SGD',${input.fulfilmentMethod},${input.requestedForDate},${input.orderNotes||null},${deliveryFeeCents},${input.checkoutRequestKey})`;
    for(const item of pricedItems)await tx`insert into customer_order_item (customer_order_item_id,customer_order_id,product_reference,product_name_snapshot,quantity,unit_price_cents) values (${randomUUID()},${orderId},${item.productId},${item.name},${item.quantity},${item.unitPriceCents})`;
    await tx`insert into order_status_event (order_status_event_id,customer_order_id,from_status,to_status,actor_subject) values (${randomUUID()},${orderId},null,'pending_payment','customer_checkout')`;
    return{orderId,totalCents,deliveryFeeCents,providerReference:null,currency:"SGD" as const,items:pricedItems};
  });
}
export async function linkStripeSession(orderId:string,sessionId:string){const rows=await database()`update customer_order set payment_provider_reference=${sessionId},updated_at_utc=now() where customer_order_id=${orderId} and status='pending_payment' and (payment_provider_reference is null or payment_provider_reference=${sessionId}) returning customer_order_id`;if(!rows.length)throw new Error("PAYMENT_LINK_FAILED")}
export async function processStripeEvent(event:{id:string;type:string;session:{id:string;client_reference_id:string|null;metadata:Record<string,string>|null;amount_total:number|null;currency:string|null;payment_status:string}}){
 const sql=database();return sql.begin(async tx=>{const duplicate=await tx`select payment_event_id from payment_event where provider='stripe' and external_event_id=${event.id}`;if(duplicate.length)return"duplicate" as const;const orderId=event.session.client_reference_id;if(!orderId||event.session.metadata?.orderId!==orderId)throw new Error("PAYMENT_MISMATCH");const rows=await tx`select status,total_amount_cents,payment_provider_reference,customer_email from customer_order where customer_order_id=${orderId} for update`;const order=rows[0];if(!order||order.payment_provider_reference!==event.session.id||Number(order.total_amount_cents)!==event.session.amount_total||event.session.currency!=="sgd")throw new Error("PAYMENT_MISMATCH");let outcome:"processed"|"ignored"="ignored";if(event.type==="checkout.session.completed"){if(event.session.payment_status!=="paid")throw new Error("PAYMENT_NOT_PAID");if(order.status==="pending_payment"){await tx`update customer_order set status='paid',version=version+1,updated_at_utc=now() where customer_order_id=${orderId}`;await tx`insert into order_status_event (order_status_event_id,customer_order_id,from_status,to_status,actor_subject) values (${randomUUID()},${orderId},'pending_payment','paid',${'stripe:'+event.id})`;await enqueueNotification(tx,orderId,"order_confirmed",order.customer_email);outcome="processed"}}else if(event.type==="checkout.session.expired"&&order.status==="pending_payment"){await tx`update customer_order set status='cancelled',version=version+1,updated_at_utc=now() where customer_order_id=${orderId}`;await tx`insert into order_status_event (order_status_event_id,customer_order_id,from_status,to_status,actor_subject) values (${randomUUID()},${orderId},'pending_payment','cancelled',${'stripe:'+event.id})`;await enqueueNotification(tx,orderId,"order_cancelled",order.customer_email);outcome="processed"}await tx`insert into payment_event (payment_event_id,provider,external_event_id,event_type,customer_order_id,processing_outcome) values (${randomUUID()},'stripe',${event.id},${event.type},${orderId},${outcome})`;return outcome})}
export async function paymentConfirmation(orderId:string,sessionId:string){const rows=await database()`select status,total_amount_cents as "totalCents",currency_code as currency,requested_for_date::text as "requestedForDate",fulfilment_method as "fulfilmentMethod" from customer_order where customer_order_id=${orderId} and payment_provider_reference=${sessionId}`;return rows[0]??null}

export async function createSyntheticOrder(actor:string){
 const sql=database();return sql.begin(async tx=>{const products=await tx`select product_id,name,price_cents from product where status='published' order by created_at_utc limit 1`;if(!products[0])throw new Error("PRODUCT_NOT_FOUND");const id=randomUUID(),reference='uat_'+randomUUID();await tx`insert into customer_order (customer_order_id,customer_name,customer_email,customer_phone,delivery_address,status,payment_method,total_amount_cents,currency_code,payment_provider_reference,fulfilment_method,requested_for_date,order_notes) values (${id},'Synthetic UAT Customer','uat-customer@example.test','+6500000000','Synthetic UAT address — not a real delivery','paid','visa',${products[0].price_cents},'SGD',${reference},'collection',current_date+14,'Synthetic test order. Do not fulfil.')`;await tx`insert into customer_order_item (customer_order_item_id,customer_order_id,product_reference,product_name_snapshot,quantity,unit_price_cents) values (${randomUUID()},${id},${products[0].product_id},${products[0].name},1,${products[0].price_cents})`;await tx`insert into order_status_event (order_status_event_id,customer_order_id,from_status,to_status,actor_subject) values (${randomUUID()},${id},null,'paid',${actor})`;await enqueueNotification(tx,id,"order_confirmed","uat-customer@example.test");return id})
}
export async function listOrders(status?:OrderStatus){const sql=database();const orders=await sql`select customer_order_id as "orderId",customer_name as "customerName",customer_email as "customerEmail",customer_phone as "customerPhone",delivery_address as "deliveryAddress",status,payment_method as "paymentMethod",total_amount_cents as "totalCents",currency_code as currency,fulfilment_method as "fulfilmentMethod",requested_for_date::text as "requestedForDate",order_notes as "orderNotes",created_at_utc as "createdAtUtc",version from customer_order where (${status??null}::text is null or status=${status??null}) order by created_at_utc desc limit 100`;if(!orders.length)return[];const ids=orders.map(row=>row.orderId);const items=await sql`select customer_order_id as "orderId",product_name_snapshot as name,quantity,unit_price_cents as "unitPriceCents" from customer_order_item where customer_order_id in ${sql(ids)} order by created_at_utc`;const events=await sql`select customer_order_id as "orderId",from_status as "fromStatus",to_status as "toStatus",occurred_at_utc as "occurredAtUtc" from order_status_event where customer_order_id in ${sql(ids)} order by occurred_at_utc`;return orders.map(order=>({...order,items:items.filter(item=>item.orderId===order.orderId),events:events.filter(event=>event.orderId===order.orderId)})) as ManagedOrder[]}
export async function updateOrderStatus(orderId:string,status:OrderStatus,actor:string,version:number){const sql=database();return sql.begin(async tx=>{const rows=await tx`select status,version,customer_email from customer_order where customer_order_id=${orderId} for update`;if(!rows[0])return undefined;if(rows[0].version!==version)throw new Error("EDIT_CONFLICT");if(!canTransitionOrder(rows[0].status as OrderStatus,status))throw new Error("INVALID_ORDER_TRANSITION");const updated=await tx`update customer_order set status=${status},version=version+1,updated_at_utc=now() where customer_order_id=${orderId} and version=${version} returning customer_order_id as "orderId",status,version`;await tx`insert into order_status_event (order_status_event_id,customer_order_id,from_status,to_status,actor_subject) values (${randomUUID()},${orderId},${rows[0].status},${status},${actor})`;await enqueueNotification(tx,orderId,`order_${status}` as "order_preparing"|"order_ready"|"order_fulfilled"|"order_cancelled",rows[0].customer_email);return updated[0]})}
export async function markOrderPaid(orderId:string,providerReference:string){await database()`update customer_order set status='paid',payment_provider_reference=${providerReference},version=version+1,updated_at_utc=now() where customer_order_id=${orderId} and status='pending_payment'`}
