// @vitest-environment node
import { afterAll, expect, it, vi } from "vitest";
import { database } from "./database";
import { getSiteContent, publishedContent, saveSiteContent } from "./site-content";
import { defaultContent } from "@/domain/site-content";
import { getProducts, saveProduct } from "./products";
vi.mock("@/server/auth", () => ({ requireAdmin: vi.fn().mockResolvedValue({ sub: "test-owner" }), AuthorizationError: class extends Error {} }));
vi.mock("@/server/admin-session", () => ({ currentAdmin: vi.fn().mockResolvedValue(null) }));
import { POST as uploadImage } from "@/app/api/admin/images/route";
import { GET as readImage } from "@/app/api/media/[id]/route";
import sharp from "sharp";
const integration = process.env.LOVELYBAKES_DATABASE_TEST === "true";
afterAll(async () => { if (integration) await database().end(); });
it.skipIf(!integration)("persists drafts, publishes atomically, rejects stale edits and edits seeded products", async () => {
  if (!/\/lovelybakes_content_test(?:_[0-9]+)?$/.test(process.env.DATABASE_URL ?? "")) throw new Error("Dedicated test database required");
  const draft = { ...defaultContent, heroTitle: "Saved test headline" };
  const v1 = await saveSiteContent(draft, 0, false, "test-owner");
  expect((await getSiteContent()).content.heroTitle).toBe(draft.heroTitle);
  expect((await publishedContent()).heroTitle).toBe(defaultContent.heroTitle);
  const v2 = await saveSiteContent(draft, v1, true, "test-owner");
  expect((await publishedContent()).heroTitle).toBe(draft.heroTitle);
  await expect(saveSiteContent(defaultContent, v1, true, "test-owner")).rejects.toThrow("EDIT_CONFLICT");
  await saveSiteContent(defaultContent, v2, false, "test-owner");
  expect((await publishedContent()).heroTitle).toBe(draft.heroTitle);
  const products = await getProducts();
  expect(products).toHaveLength(6);
  const original = products[0];
  await saveProduct({ ...original, name: "Updated existing cake", priceCents: 9900 }, "test-owner", original.id, original.version);
  const updated = (await getProducts()).find((product) => product.id === original.id)!;
  expect(updated.name).toBe("Updated existing cake");
  expect(updated.priceCents).toBe(9900);
  expect(updated.version).toBe(original.version + 1);
  await expect(saveProduct(original, "test-owner", original.id, original.version)).rejects.toThrow("EDIT_CONFLICT");
  const imageBytes = await sharp({ create: { width: 32, height: 32, channels: 3, background: "pink" } }).png().toBuffer();
  const upload = await uploadImage(new Request("http://127.0.0.1:3000/api/admin/images", { method: "POST", body: new Uint8Array(imageBytes), headers: { "Content-Type": "image/png" } }));
  expect(upload.status).toBe(201);
  const { imageUrl } = await upload.json();
  const imageRequest = () => readImage(new Request("http://127.0.0.1:3000" + imageUrl), { params: Promise.resolve({ id: imageUrl.split("/").pop() }) });
  const latest = await getSiteContent();
  const imageContent = { ...defaultContent, heroImage: imageUrl };
  const imageVersion = await saveSiteContent(imageContent, latest.version, false, "test-owner");
  expect((await imageRequest()).status).toBe(404);
  await saveSiteContent(imageContent, imageVersion, true, "test-owner");
  const publicImage = await imageRequest();
  expect(publicImage.status).toBe(200);
  expect(publicImage.headers.get("content-type")).toBe("image/webp");
  expect((await sharp(Buffer.from(await publicImage.arrayBuffer())).metadata()).width).toBe(32);

});
