import { adminOrderUpdateSchema, orderStatusSchema } from "@/domain/order";
import { requireAdmin, AuthorizationError } from "@/server/auth";
import { listOrders,updateOrderStatus,createSyntheticOrder } from "@/server/orders";
import { refundOrder } from "@/server/orders";
import { refundRequestSchema } from "@/domain/refund";
import { deliverOrderNotifications } from "@/server/notifications";
import { problem,safeJson } from "@/server/http";
function failure(error:unknown){if(error instanceof AuthorizationError)return problem(error.status,"AUTHORIZATION_FAILED",error.message);if(error instanceof Error&&error.message==="INVALID_ORDER_TRANSITION")return problem(409,"INVALID_ORDER_TRANSITION","Complete each fulfilment step in order.");if(error instanceof Error&&error.message==="EDIT_CONFLICT")return problem(409,"EDIT_CONFLICT","This order changed in another window. Reload before updating.");if(error instanceof Error&&["REFUND_NOT_ALLOWED","ALREADY_REFUNDED","REFUNDS_DISABLED"].includes(error.message))return problem(409,error.message,"Only an unfulfilled Stripe order with a captured balance can be refunded while refunds are enabled.");if(error instanceof Error&&error.message==="NOT_FOUND")return problem(404,"ORDER_NOT_FOUND","Order not found.");return problem(503,"SERVICE_UNAVAILABLE","Order service is temporarily unavailable.")}
export async function GET(request:Request){try{await requireAdmin(request);const value=new URL(request.url).searchParams.get("status"),status=value===null?undefined:orderStatusSchema.safeParse(value);if(status&&!status.success)return problem(400,"INVALID_STATUS","Unknown order status.");return Response.json({orders:await listOrders(status?.data)},{headers:{"Cache-Control":"no-store"}})}catch(error){return failure(error)}}
export async function POST(request:Request){try{const actor=await requireAdmin(request);if(!actor.sub)return problem(403,"MISSING_SUBJECT","Identified administrator required.");const parsed=await safeJson(request);if(!parsed||typeof parsed!=="object"||Object.keys(parsed).length!==1||!("createSynthetic" in parsed)||(parsed as {createSynthetic:unknown}).createSynthetic!==true)return problem(400,"INVALID_REQUEST","Only synthetic UAT orders can be created here.");return Response.json({orderId:await createSyntheticOrder(actor.sub)},{status:201})}catch(error){return failure(error)}}
export async function PATCH(request:Request){try{const actor=await requireAdmin(request);if(!actor.sub)return problem(403,"MISSING_SUBJECT","Identified administrator required.");const input=adminOrderUpdateSchema.safeParse(await safeJson(request));if(!input.success)return problem(400,"INVALID_UPDATE","A valid order, version and status are required.");const order=await updateOrderStatus(input.data.orderId,input.data.status,actor.sub,input.data.version);if(order)await deliverOrderNotifications(input.data.orderId).catch(()=>undefined);return order?Response.json({order},{headers:{"Cache-Control":"no-store"}}):problem(404,"ORDER_NOT_FOUND","Order not found.")}catch(error){return failure(error)}}
export async function DELETE(request:Request){try{const actor=await requireAdmin(request);if(!actor.sub)return problem(403,"MISSING_SUBJECT","Identified administrator required.");const input=refundRequestSchema.safeParse(await safeJson(request));if(!input.success)return problem(400,"INVALID_REFUND","A valid order, version and cancellation reason are required.");const refund=await refundOrder(input.data.orderId,input.data.reason,actor.sub,input.data.version);await deliverOrderNotifications(input.data.orderId).catch(()=>undefined);return Response.json({refund},{headers:{"Cache-Control":"no-store"}})}catch(error){return failure(error)}}
