"use client";
import { useState } from "react";
import { formatPrice } from "@/lib/catalog";
import type { OrderingRule } from "@/domain/ordering";
async function body(response: Response) { const value=await response.json(); if(!response.ok) throw new Error(value.error?.message??"Request failed."); return value; }
export function OrderingEditor({ initial }: { initial: OrderingRule }) {
 const [rule,setRule]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const set=<K extends keyof OrderingRule>(key:K,value:OrderingRule[K])=>setRule(current=>({...current,[key]:value}));
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");setMessage("");try{const result=await body(await fetch("/api/admin/ordering",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(rule)}));setRule(current=>({...current,version:result.version}));setMessage("Ordering rules saved and visible in the shop.");}catch(cause){setError(cause instanceof Error?cause.message:"Save failed.");}finally{setBusy(false)}}
 return <main className="admin-main"><div className="admin-heading"><div><h1>Ordering rules</h1><p>Control fulfilment, fees, notice periods and unavailable dates.</p></div></div>{error&&<div className="admin-message admin-error" role="alert">{error}</div>}{message&&<div className="admin-message" role="status">{message}</div>}<section className="admin-panel"><form className="admin-form" onSubmit={save}><fieldset disabled={busy} className="content-fields"><legend>Fulfilment methods</legend><label className="admin-checkbox"><input type="checkbox" checked={rule.collectionEnabled} onChange={e=>set("collectionEnabled",e.target.checked)}/>Collection</label><label className="admin-checkbox"><input type="checkbox" checked={rule.deliveryEnabled} onChange={e=>set("deliveryEnabled",e.target.checked)}/>Delivery</label><div className="admin-two"><label className="admin-field">Minimum order (SGD)<input type="number" min="0" max="10000" step="0.01" value={(rule.minimumOrderCents/100).toFixed(2)} onChange={e=>set("minimumOrderCents",Math.round(Number(e.target.value)*100))}/><small>Current minimum: {formatPrice(rule.minimumOrderCents)}</small></label><label className="admin-field">Delivery fee (SGD)<input type="number" min="0" max="100" step="0.01" value={(rule.deliveryFeeCents/100).toFixed(2)} onChange={e=>set("deliveryFeeCents",Math.round(Number(e.target.value)*100))}/></label><label className="admin-field">Minimum notice (days)<input type="number" min="1" max="90" value={rule.leadTimeDays} onChange={e=>set("leadTimeDays",Number(e.target.value))}/></label><label className="admin-field">Book up to (days ahead)<input type="number" min={rule.leadTimeDays} max="365" value={rule.maximumAdvanceDays} onChange={e=>set("maximumAdvanceDays",Number(e.target.value))}/></label></div><label className="admin-field">Collection instructions<textarea maxLength={500} required value={rule.collectionInstructions} onChange={e=>set("collectionInstructions",e.target.value)}/></label><label className="admin-field">Delivery area / instructions<textarea maxLength={500} required value={rule.deliveryArea} onChange={e=>set("deliveryArea",e.target.value)}/></label><label className="admin-field">Unavailable dates<textarea placeholder="2026-12-25, 2026-12-26" value={rule.blackoutDates.join(", ")} onChange={e=>set("blackoutDates",e.target.value.split(/[\s,]+/).filter(Boolean))}/><small>Use YYYY-MM-DD, separated by commas. These dates cannot be selected.</small></label></fieldset><div className="admin-actions"><span>Changes apply immediately to the UAT shop.</span><button className="primary-button" disabled={busy}>{busy?"Saving…":"Save ordering rules"}</button></div></form></section></main>;
}
